import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Sidebar } from './component/sidebar/Sidebar';
import { ThemeSwitch } from './component/ThemeSwitch';
import { CartProvider } from './context/CartContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'QuickCart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='flex items-center justify-between bg-linear-to-br from-[#2563EB] to-[#1D4ED8] p-3 sticky top-0 z-10 dark:bg-linear-to-br dark:from-neutral-900 dark:to-neutral-800'>
          <h1 className='text-white text-2xl tracking-widest space-x-2.5 ml-2'>
            QuickCart
          </h1>
          <ThemeSwitch />
        </header>

        <div className='flex min-h-screen'>
          <CartProvider>
            <aside className='w-16 shrink-0 border-r'>
              <Sidebar />
            </aside>

            <main className='flex-1 p-6 overflow-y-auto bg-[#F8FAFC]! dark:bg-linear-to-br dark:from-neutral-800 dark:to-neutral-600'>
              {children}
            </main>
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
