import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Sidebar } from './component/sidebar/Sidebar';
import { ThemeSwitch } from './component/ThemeSwitch';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='flex items-center justify-between bg-linear-to-br from-blue-400 to-blue-600 p-3 sticky top-0 z-10'>
          <h1 className='text-white'>Product Shop</h1>
          <ThemeSwitch />
        </header>

        <div className='flex min-h-screen'>
          <aside className='w-20 shrink-0'>
            <Sidebar />
          </aside>

          <main className='flex flex-1 flex-col items-center justify-between bg-white overflow-y-auto'>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
